name: CI

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  rust:
    name: Rust checks
    runs-on: ubuntu-latest
    env:
      CARGO_TERM_COLOR: always
      PYO3_PYTHON: python3
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy
      - name: Run cargo fmt
        run: cargo fmt --all -- --check
      - name: Run cargo clippy
        run: cargo clippy --all-targets --all-features
      - name: Run cargo tests
        run: cargo test --all-features --all-targets

  python:
    name: Python packaging
    runs-on: ubuntu-latest
    env:
      PYO3_PYTHON: python3
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install build dependencies
        shell: bash
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install --upgrade pip
          pip install maturin pytest
      - name: Build extension in development mode
        shell: bash
        run: |
          source .venv/bin/activate
          maturin develop --release -F python
      - name: Run Python tests
        shell: bash
        run: |
          source .venv/bin/activate
          pytest -q
      - name: Build distributable artifacts
        shell: bash
        run: |
          source .venv/bin/activate
          maturin build --release -F python --skip-auditwheel
